name: Steam Idle
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  idle:
    runs-on: ubuntu-latest
    steps:
      - name: Steam Idle Action
        uses: sst-scout/steam-idle-action@v1.0.3
        with:
          username: ${{ secrets.STEAM_USERNAME }}
          password: ${{ secrets.STEAM_PASSWORD }}
          # Айди для War Thunder
          appids: '236390'
