name: Steam Idle
on:
  workflow_dispatch:

jobs:
  idle:
    runs-on: ubuntu-latest
    steps:
      - name: Run Idle
        uses: sst-scout/steam-idle-action@v1.0.3
        with:
          username: ${{ secrets.STEAM_USERNAME }}
          password: ${{ secrets.STEAM_PASSWORD }}
          appids: '236390'
